### ISSUE TITLE
IOS 13 Dark Mode

### ISSUE THREAD

**Issue by DK-Web** [Wilsonator5000/AppleWelcomeScreen#3]
Hi, thanks for your AppleWelcomeScreen. Unfortunately, this is broken in IOS 13 Darkmode, since only part of the background is black. Can you take a look at this please? Maybe you can set the backgrounds via .systemBackground and the font by .label.
Thank you and best regards

**Comment by DK-Web** [comment]
@Wilsonator5000 I really need your support, because I have to upload an update to the appstore because my app in IOS 13 is broken! Ask for a quick answer! Thank you very much

**Comment by Wilsonator5000** [comment]
Hey @DK-Web,

Sorry for the late reply. I might be able to get to it later today if I have time, but if you want you can submit a pull request and I'll be happy to merge it!

Thanks,
Wilson

**Comment by DK-Web** [comment]
Hi Wilson, thanks for your quick reply. Unfortunately I can not fix the error. Had already tried without success.

The background of the item cells is automatically set to black by DarkMode, but the item texts are no longer visible because they are black.

There must be a way to change the colors of the entire View background and the Item-Table + Cells to ".systemBackground" as well as the text color of the individual items and descriptions to ".label".

I would be very grateful if you can implement that quickly.

Thank you so much!

**Comment by Wilsonator5000** [comment]
I just pushed a new version (1.0.2) that should work with dark mode. Try it out and let me know if you run into any issues! Thanks for helping out 😄

**Comment by DK-Web** [comment]
Hi Wilson, thank you for your quick update. Unfortunately I can not install this. I get this error message:

`Analyzing dependencies
Downloading dependencies
Installing AppleWelcomeScreen (1.0.2)

[!] Error installing AppleWelcomeScreen
[!] /usr/bin/git clone https://github.com/Wilsonator5000/AppleWelcomeScreen.git /var/folders/49/k2kb5k6s3kj0qtxrg5tb_c880000gn/T/d20190928-5499-1rjycwp --template= --single-branch --depth 1 --branch 1.0.2

Cloning into '/var/folders/49/k2kb5k6s3kj0qtxrg5tb_c880000gn/T/d20190928-5499-1rjycwp'...
dyld: lazy symbol binding failed: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib

dyld: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib`

Do you have an idea what's going on there?

**Comment by DK-Web** [comment]
Hi Wilson, I could fix the problem. The PATH was changed in the .bash_profile file for whatever reason.

Good job! The DarkMode works very well with your AppleWelcomeScreen.

Now, i have another question.

Since the welcomescreen is now displayed as a card and the user can swipe it down, I need a way to run a callback. So then, when the view was swiped down.

Currently, when the user clicks on the "ok close" button, a UserDefault is set so that the view does not reappear. Swiped the user the view down, then the view comes back with every app restart.

How can I use a callback for closing per swipe?

Thank you so much!

**Comment by DK-Web** [comment]
Okay, I have it.

This change changes the card view to the previous full view:
            
let vc = AWSViewController()
vc.configuration = configuration
vc.modalPresentationStyle = .fullScreen
self.present(vc, animated: true)
